env:
  es2021: true
  node: true
  jest: true
  browser: true
extends: 
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0
  no-param-reassign: 0
  import/no-extraneous-dependencies: 
    - error
    - devDependencies: 
        - './webpack.config.js'